name: Telegram Bot
on:
  workflow_dispatch:
    inputs:
      message: {description: 'Message', required: true}
      chat_id: {description: 'Chat ID', required: true}
  schedule:
    - cron: '0 17 * * *'
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: {python-version: '3.10'}
      - run: pip install -r requirements.txt
      - name: Run
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GCAL_TOKEN: ${{ secrets.GCAL_TOKEN }}
          TRIGGER: ${{ github.event_name }}
          MSG: ${{ github.event.inputs.message }}
        run: python3 main.py
